version: 1.0.{build}
branches:
  only:
  - dev
build_script:
- cmd: build.cmd
test: off
artifacts:
- path: artifacts/packages/release/*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/alhardy/api/v2/package 
  skip_symbols: true
  on:
    branch: dev